-- V2.14: verified 2026 regulatory-source updates and customer-facing rule metadata.
-- This migration records source/version metadata; it does not replace legal review.
CREATE TABLE IF NOT EXISTS regulatory_updates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  authority TEXT NOT NULL,
  source_code TEXT NOT NULL,
  title TEXT NOT NULL,
  published_on DATE NOT NULL,
  effective_from DATE,
  applies_to TEXT NOT NULL,
  summary TEXT NOT NULL,
  implementation_mode TEXT NOT NULL DEFAULT 'GUIDANCE',
  source_url TEXT,
  version TEXT NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_regulatory_updates_authority_date ON regulatory_updates(authority, published_on DESC);
CREATE INDEX IF NOT EXISTS idx_regulatory_updates_applies ON regulatory_updates(applies_to, effective_from);

INSERT INTO regulatory_updates
(authority, source_code, title, published_on, effective_from, applies_to, summary, implementation_mode, source_url, version)
VALUES
('RBI/FEMA','FEMA 23(R)/(8)/2026-RB','Export of Goods and Services (First Amendment) Regulations, 2026','2026-06-05','2026-06-05','EXPORT','For the then-existing FEMA export regulations, the export-realisation period in Regulation 9 was amended from fifteen months to nine months. The 2026 consolidated Export and Import of Goods and Services Regulations effective 2026-10-01 must be evaluated for transactions/events falling under that framework.','RULE_VERSIONED','https://www.rbi.org.in/scripts/BS_FemaNotifications.aspx?Id=13467','2026.06'),
('RBI/FEMA','FEMA 395(4)/2026-RB','Mode of Payment and Reporting of Non-Debt Instruments (Amendment) Regulations, 2026','2026-06-13','2026-06-13','FDI','Updated payment/reporting provisions for specified NRI/OCI investments and reporting of individual foreign investor transactions; use only for applicable FDI/NRI/OCI scenarios.','RULE_VERSIONED','https://www.rbi.org.in/scripts/BS_FemaNotifications.aspx?Id=13484','2026.06'),
('RBI/FEMA','FEMA 23(R)/2026-RB','Export and Import of Goods and Services Regulations, 2026','2026-01-16','2026-10-01','EXPORT,IMPORT,MTT','Consolidated 2026 framework with EDF, EDPMS/IDPMS monitoring, export-realisation timelines, import-payment monitoring, advances and MTT provisions.','RULE_VERSIONED','https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=13277&Mode=0','2026.10'),
('RBI/FEMA','FEMA 3(R)(1)/2026-RB','Borrowing and Lending (First Amendment) Regulations, 2026','2026-02-16','2026-02-16','ECB,TRADE_CREDIT','ECB/trade-credit regulatory source updated; product rules must be evaluated from the current RBI framework rather than historical hard-coded limits.','RULE_VERSIONED','https://m.rbi.org.in/scripts/Bs_FemaNotifications.aspx','2026.02'),
('RBI/FEMA','FEMA 9(R)/2026-RB','Guarantees Regulations, 2026','2026-01-12','2026-01-12','BG','New FEMA guarantees regulatory source; guarantee structure and reporting applicability must be evaluated by transaction facts and instrument wording.','RULE_VERSIONED','https://m.rbi.org.in/scripts/Bs_FemaNotifications.aspx','2026.01'),
('FEDAI','SPL-06/Trade/2026','e-BRC against DTA supply to SEZ/SEA','2026-09-07','2026-09-07','EXP_GOODS,EXP_SERVICE','DTA-to-SEZ supplies are exports under the SEZ Act and should not be reported on DGFT as FTP Chapter 7 deemed exports merely because a FETERS/R-Return purpose code is used; e-BRC issuance and DGFT IRM data should follow the underlying transaction and applicable DGFT process.','GUIDANCE','https://fedai.org.in/DocumentUploadFiles/SpecialCircular/Spl%20Circular%2006%20Export%20to%20SEZ.pdf','2026.09'),
('FEDAI','SPL-05/Trade/2026','Freight forwarder foreign-exchange billing/remittance clarification','2026-08-21','2026-08-21','EXP_SERVICE,IMPORT','Where a resident intermediary acts as pass-through for a foreign-exchange liability to a non-resident, the pass-through amount should represent the underlying liability; the intermediary should not add exchange margin/mark-up to that foreign-exchange pass-through. Charges for intermediary services not remitted to a non-resident should be denominated in INR.','GUIDANCE','https://fedai.org.in/DocumentUploadFiles/SpecialCircular/Spl%20Circular-05_trade_2026.pdf','2026.08'),
('FEDAI','SPL-04/Trade/2026','Payment Aggregator – Cross Border (PA-CB) remittance and EDPMS/IDPMS closure','2026-08-14','2026-08-14','EXP_GOODS,EXP_SERVICE,IMPORT','PA-CBs should provide transaction information/documents needed for EDPMS/IDPMS closure to the relevant AD bank; AD banks maintaining PA-CB collection accounts are expected to have automated processes to fetch prescribed information.','GUIDANCE','https://fedai.org.in/DocumentUploadFiles/SpecialCircular/Spl%20Circular%2004%20PACB.pdf','2026.08'),
('FEDAI','SPL-03/Trade/2026','Manual shipping bills – Gem and Jewellery exhibitions','2026-08-04','2026-08-04','EXP_GOODS','Where manually issued Customs-certified shipping bills for qualifying hand-carried exhibition/export-promotion goods do not reflect in EDPMS, the exporter can approach the AD bank with the certified shipping bill and supporting documents; the AD bank may approach RBI regional office after due diligence.','GUIDANCE','https://fedai.org.in/DocumentUploadFiles/SpecialCircular/SPL-03_Trade_2026.pdf','2026.08'),
('FEDAI','SPL-02/MTT/2026','Merchanting Trade interpretation under FTP 2023','2026-08-04','2026-08-04','MTT','RBI clarified that the MTT goods-permissibility test should align with FTP 2023 paragraph 2.39: merchanting trade is permitted subject to RBI guidelines, except goods/items in CITES and SCOMET lists.','RULE_VERSIONED','https://fedai.org.in/DocumentUploadFiles/SpecialCircular/SPL_02_2026_MTT.pdf','2026.08'),
('FEDAI','AR Circular 03/2026','Amendment in FEDAI Rules – faster cross-border inward payments','2026-09-07','2026-08-20','EXP_GOODS,EXP_SERVICE,IMPORT','FEDAI Rules 2.5(b) and 4.5 were amended effective 20-Aug-2026. Subject to confirmation, reconciliation, FEMA and internal requirements, banks should endeavour to credit export proceeds received during market hours the same business day and after market hours the next business day; inward payment messages should be intimated promptly and reconciliation is expected near-real-time or periodically, normally not exceeding one hour.','GUIDANCE','https://fedai.org.in/DocumentUploadFiles/ARCircular/AR%20Circular%20No.%2003%2007%20September%202026.pdf','2026.08'),
('DGFT','Notification 05/2026-27','Amendment to FTP 2023 paragraph 2.62 – Certificates of Origin','2026-04-07','2026-04-07','EXPORT','Preferential/non-preferential Certificate of Origin issuance is to follow DGFT-authorised agencies and prescribed procedures; IEC holders using CoOs must use the same invoice number in CoO and Shipping Bill for automated verification.','RULE_VERSIONED','https://content.dgft.gov.in/Website/dgftprod/edd8a29b-bf8b-440d-a102-3f4048c965cc/Notification%20No.%2005%20English%20dated%2007.04.2026%20signed.pdf','2026.04'),
('DGFT','Notification 24/2026-27','ITC(HS) 2022 Schedule-I import policy aligned with Finance Act 2026','2026-07-22','2026-07-22','IMPORT','Import-policy ITC(HS) codes/descriptions/conditions were inserted, deleted, amended, split or merged to align with Finance Act 2026. HSN/ITC suggestions must use the current versioned DGFT dataset.','RULE_VERSIONED','https://dgft.gov.in','2026.07'),
('DGFT','Notification 26/2026-27','ITC(HS) 2022 Schedule-II export policy aligned with Finance Act 2026','2026-07-27','2026-07-27','EXPORT','Export-policy ITC(HS) notes and codes were harmonised with Finance Act 2026. Classification remains a suggestion/reference and must not be treated as a legal conclusion.','RULE_VERSIONED','https://dgft.gov.in','2026.07'),
('DGFT','Notification 27/2026-27','Inventory-based Cross-border E-Commerce Export Framework','2026-08-05','2026-08-05','EXPORT','DGFT introduced an inventory-based cross-border e-commerce export framework under FTP 2023; applicable workflow should be surfaced only when the transaction is identified as qualifying e-commerce inventory export.','GUIDANCE','https://dgft.gov.in','2026.08'),
('DGFT','Notification 30/2026-27','Amendment to FTP 2023 paragraphs 2.52 and 2.53','2026-08-20','2026-08-20','EXPORT','Recent FTP procedural provisions were amended; applicable conditions should be evaluated against the transaction type and current DGFT procedures.','GUIDANCE','https://dgft.gov.in','2026.08')
ON CONFLICT DO NOTHING;
