package main

// RegulatoryUpdate is the customer-facing, versioned summary of verified regulatory
// sources loaded for the rules/knowledge layer. It is deliberately descriptive;
// it is not a legal opinion and does not replace the source document.
type RegulatoryUpdate struct {
	Authority      string `json:"authority"`
	SourceCode     string `json:"source_code"`
	Title          string `json:"title"`
	PublishedOn    string `json:"published_on"`
	EffectiveFrom  string `json:"effective_from,omitempty"`
	AppliesTo      string `json:"applies_to"`
	Summary        string `json:"summary"`
	Implementation string `json:"implementation_mode"`
	SourceURL      string `json:"source_url,omitempty"`
	Version        string `json:"version"`
}

var regulatoryUpdates2026 = []RegulatoryUpdate{
	{Authority: "RBI/FEMA", SourceCode: "FEMA 23(R)/(8)/2026-RB", Title: "Export of Goods and Services (First Amendment) Regulations, 2026", PublishedOn: "2026-06-05", EffectiveFrom: "2026-06-05", AppliesTo: "EXPORT", Summary: "Legacy FEMA export-regulation amendment changed the Regulation 9 realisation period from 15 months to 9 months. The consolidated 2026 export/import framework effective 2026-10-01 is separately versioned.", Implementation: "RULE_VERSIONED", SourceURL: "https://www.rbi.org.in/scripts/BS_FemaNotifications.aspx?Id=13467", Version: "2026.06"},
	{Authority: "RBI/FEMA", SourceCode: "FEMA 23(R)/2026-RB", Title: "Export and Import of Goods and Services Regulations, 2026", PublishedOn: "2026-01-16", EffectiveFrom: "2026-10-01", AppliesTo: "EXPORT,IMPORT,MTT", Summary: "Consolidated framework for EDF, EDPMS/IDPMS monitoring, export realisation, import payment monitoring, advances and MTT.", Implementation: "RULE_VERSIONED", SourceURL: "https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=13277&Mode=0", Version: "2026.10"},
	{Authority: "FEDAI", SourceCode: "SPL-06/Trade/2026", Title: "e-BRC against DTA supply to SEZ/SEA", PublishedOn: "2026-09-07", EffectiveFrom: "2026-09-07", AppliesTo: "EXPORT", Summary: "DTA-to-SEZ supplies are exports under the SEZ Act and should not be treated as FTP Chapter 7 deemed exports merely because of a FETERS/R-Return purpose code. e-BRC/DGFT handling follows the underlying transaction.", Implementation: "GUIDANCE", SourceURL: "https://fedai.org.in/DocumentUploadFiles/SpecialCircular/Spl%20Circular%2006%20Export%20to%20SEZ.pdf", Version: "2026.09"},
	{Authority: "FEDAI", SourceCode: "SPL-04/Trade/2026", Title: "PA-CB remittance and EDPMS/IDPMS closure", PublishedOn: "2026-08-14", EffectiveFrom: "2026-08-14", AppliesTo: "EXPORT,IMPORT", Summary: "PA-CBs should provide information/documents needed for EDPMS/IDPMS closure; AD banks maintaining PA-CB collection accounts are expected to have automated information-fetch processes.", Implementation: "GUIDANCE", SourceURL: "https://fedai.org.in/DocumentUploadFiles/SpecialCircular/Spl%20Circular%2004%20PACB.pdf", Version: "2026.08"},
	{Authority: "FEDAI", SourceCode: "SPL-03/Trade/2026", Title: "Manual shipping bills – Gem & Jewellery exhibitions", PublishedOn: "2026-08-04", EffectiveFrom: "2026-08-04", AppliesTo: "EXPORT", Summary: "Manual Customs-certified shipping bills not reflected in EDPMS may be taken to the AD bank with supporting documents; after due diligence the AD bank may approach RBI regional office for upload facilitation.", Implementation: "GUIDANCE", SourceURL: "https://fedai.org.in/DocumentUploadFiles/SpecialCircular/SPL-03_Trade_2026.pdf", Version: "2026.08"},
	{Authority: "FEDAI", SourceCode: "SPL-02/MTT/2026", Title: "MTT interpretation under FTP 2023", PublishedOn: "2026-08-04", EffectiveFrom: "2026-08-04", AppliesTo: "MTT", Summary: "MTT goods-permissibility should align with FTP 2023 paragraph 2.39, subject to RBI guidelines and excluding CITES/SCOMET goods.", Implementation: "RULE_VERSIONED", SourceURL: "https://fedai.org.in/DocumentUploadFiles/SpecialCircular/SPL_02_2026_MTT.pdf", Version: "2026.08"},
	{Authority: "FEDAI", SourceCode: "AR Circular 03/2026", Title: "FEDAI Rules amendment – faster cross-border inward payments", PublishedOn: "2026-09-07", EffectiveFrom: "2026-08-20", AppliesTo: "EXPORT,IMPORT", Summary: "Rules 2.5(b) and 4.5 were amended. Subject to confirmation, reconciliation, FEMA and internal requirements, banks should endeavour to credit qualifying inward/export proceeds the same or next business day and provide prompt payment intimation.", Implementation: "GUIDANCE", SourceURL: "https://fedai.org.in/DocumentUploadFiles/ARCircular/AR%20Circular%20No.%2003%2007%20September%202026.pdf", Version: "2026.08"},
	{Authority: "DGFT", SourceCode: "Notification 05/2026-27", Title: "FTP 2023 paragraph 2.62 – Certificates of Origin", PublishedOn: "2026-04-07", EffectiveFrom: "2026-04-07", AppliesTo: "EXPORT", Summary: "CoO issuance follows DGFT-authorised agencies and prescribed procedures; IEC holders using CoOs must use the same invoice number in CoO and Shipping Bill for automated verification.", Implementation: "RULE_VERSIONED", SourceURL: "https://content.dgft.gov.in/Website/dgftprod/edd8a29b-bf8b-440d-a102-3f4048c965cc/Notification%20No.%2005%20English%20dated%2007.04.2026%20signed.pdf", Version: "2026.04"},
	{Authority: "DGFT", SourceCode: "Notification 24/2026-27", Title: "ITC(HS) 2022 Schedule-I import policy aligned with Finance Act 2026", PublishedOn: "2026-07-22", EffectiveFrom: "2026-07-22", AppliesTo: "IMPORT", Summary: "Import ITC(HS) codes, descriptions and policy conditions were updated. The HSN engine must use the current versioned DGFT dataset.", Implementation: "RULE_VERSIONED", SourceURL: "https://dgft.gov.in", Version: "2026.07"},
	{Authority: "DGFT", SourceCode: "Notification 26/2026-27", Title: "ITC(HS) 2022 Schedule-II export policy aligned with Finance Act 2026", PublishedOn: "2026-07-27", EffectiveFrom: "2026-07-27", AppliesTo: "EXPORT", Summary: "Export ITC(HS) notes and codes were harmonised with Finance Act 2026. Classification remains a suggestion/reference only.", Implementation: "RULE_VERSIONED", SourceURL: "https://dgft.gov.in", Version: "2026.07"},
	{Authority: "DGFT", SourceCode: "Notification 27/2026-27", Title: "Inventory-based Cross-border E-Commerce Export Framework", PublishedOn: "2026-08-05", EffectiveFrom: "2026-08-05", AppliesTo: "EXPORT", Summary: "Inventory-based cross-border e-commerce exports are now covered by a specific FTP framework; surface only for qualifying transactions.", Implementation: "GUIDANCE", SourceURL: "https://dgft.gov.in", Version: "2026.08"},
}
